# Generated by Django 4.1.1 on 2022-09-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miblog.categoria",
            ),
        ),
    ]
