# Generated by Django 4.1.1 on 2022-10-07 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contenido",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
