# Generated by Django 4.1.1 on 2022-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0002_alter_post_contenido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.AddField(
            model_name="post",
            name="imagen",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
