# Generated by Django 4.1.1 on 2022-09-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0002_alter_post_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miblog.autor",
            ),
        ),
    ]
