# Generated by Django 4.1.1 on 2022-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0003_remove_post_autor_post_imagen"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Autor",
        ),
        migrations.AddField(
            model_name="post",
            name="autor",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
