# Generated by Django 4.1.1 on 2022-10-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miblog", "0004_delete_autor_post_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="descripcion",
            field=models.CharField(max_length=100),
        ),
    ]
